[tool.poetry]
name = "curseforge"
version = "2.0.0"
description = "A no-compromise CurseForge API wrapper binding for python"
authors = ["Advik <advik.b@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9.7"
pybind11 = "^2.13.6"

[build-system]
requires = ["scikit-build-core", "pybind11"]
build-backend = "scikit_build_core.build"

[project]
name = "curseforge"
version = "2.0.0"