
name: Test on multiple OS

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        if [ $RUNNER_OS == 'Windows' ]; then
          python -m pip install --upgrade pip
        else
          pip install --upgrade pip
        fi

    - name: Run tests
      run: |
        sh ./build.sh
        pip install --force-reinstall dist/*.whl
        python test.py